### ISSUE TITLE
Horizontal rules are directly underneath images 

### ISSUE THREAD

**Issue by dulldesk** [floundernews/floundernews.github.io#15]
In issues, horizontal rules are directly underneath the images; as a result, they are not the easiest to detect. 

![image](https://user-images.githubusercontent.com/54601393/107166507-3b836b00-6984-11eb-85f3-45919e85a668.png)

On another note, the `<hr>` gray does not contrast well with the green of the background ~~but maybe that's just my eyes~~.

**Comment by skyflaren** [comment]
I'd agree with the `<hr>` color needing to be changed, potentially to `#2a5457`
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/45515570/107167631-586d6d80-6987-11eb-882e-4ad5d3b3ca14.png">
