### ISSUE TITLE
Broken Article Scrolling on the Issue Page (on some browsers)

### ISSUE THREAD

**Issue by dulldesk** [floundernews/floundernews.github.io#93]
The anchor links on a news issue's table of contents do not jump to the respective article on Chrome (though it works on Firefox).

[Link to a sample issue](https://floundernews.tk/2021/12/)

Possible (and probable) solution:
> need both name and id attribute to match

**Comment by ApocalypseCalculator** [comment]
After screwing around for a little bit, I found that when you paste the entire HTML into the browser again (replacing the old one), it works. 
One possible explanation for this is the slow loading for images which results in the positions of the elements not getting updated by the browser. However I cannot confirm this. 

Here is a workaround I made which you can paste into your browser: 
```js
window.scroll(0, window.pageYOffset + $(window.location.hash).getBoundingClientRect().top)
```
